runtime: python311

entrypoint: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --logger.level=error

instance_class: F2

env_variables:
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"

handlers:
  - url: /.*
    script: auto
    secure: always
